#ifndef SMART_POD_APP_CONFIG_H
#define SMART_POD_APP_CONFIG_H

#pragma once

#include <string>

using namespace std;

// must be an integer value
#define SERVER_PORT 9080

// logs
#define INFO_LABEL "[INFO] "
#define ERROR_LABEL "[ERROR] "

// notifications types
#define GENERAL_NOTIFICATION "GENERAL_NOTIFICATION"
#define WATER_NOTIFICATION "WATER_NOTIFICATION"
#define SOIL_HEALTH_NOTIFICATION "SOIL_HEALTH_NOTIFICATION"
#define SOIL_MOISTURE_NOTIFICATION "SOIL_MOISTURE_NOTIFICATION"
#define AIR_QUALITY_NOTIFICATION "AIR_QUALITY_NOTIFICATION"

#endif //SMART_POD_APP_CONFIG_H
